### ISSUE TITLE
There is a Pickle Protocol 5 issue 

### ISSUE THREAD

**Issue by jzxwang** [toni-heittola/dcase2020_task1_baseline#7]
`Traceback (most recent call last):
  File "task1b.py", line 692, in <module>
    sys.exit(main(sys.argv))
  File "task1b.py", line 233, in main
    overwrite=overwrite
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/at007484/code/Users/dcase2020_task1_baseline-master/task1a.py", line 637, in do_learning
    init_parameters=init_parameters,
  File "/anaconda/envs/tf-dcase-old/lib/python3.7/site-packages/dcase_util/processors/processing_chain.py", line 359, in push_processor
    'output_type': output_type,
  File "/anaconda/envs/tf-dcase-old/lib/python3.7/site-packages/dcase_util/processors/processing_chain.py", line 27, in __init__
    self.init_processor_class()
  File "/anaconda/envs/tf-dcase-old/lib/python3.7/site-packages/dcase_util/processors/processing_chain.py", line 54, in init_processor_class
    self.processor_class = eval('processor_module.' + processor_name.split('.')[-1])(**processor_init_parameters)
  File "/anaconda/envs/tf-dcase-old/lib/python3.7/site-packages/dcase_util/processors/data.py", line 448, in __init__
    normalizer = Normalizer().load(filename=filename)
  File "/anaconda/envs/tf-dcase-old/lib/python3.7/site-packages/dcase_util/containers/containers.py", line 64, in load
    self.__dict__.update(Serializer.load_cpickle(filename=self.filename))
  File "/anaconda/envs/tf-dcase-old/lib/python3.7/site-packages/dcase_util/files/serialization.py", line 122, in load_cpickle
    return pickle.load(open(filename, "rb"))
ValueError: unsupported pickle protocol: 5`

**Comment by jzxwang** [comment]
hi, there, I would like to reproduce this task and face the error above. I google that protocol, google said protocol 5 only python 3.8 above is supported, but if I use python3.8, the TensorFlow version can not be supported.

**Comment by jzxwang** [comment]
Hi there, the issue is resolved, I tried to install python3.6, this version is suited for the program.
